console.log("Hello Winc");
let naam = 'Janna';
//let if;
console.log(naam);
console.log(4+4);
console.log("4"+"4");
console.log(3-2);
console.log(2*4);
console.log(12/3);
console.log(100%12);
let leeftijd = 24;
console.log(typeof leeftijd);